Repository DEFRA/defra-ruby-mocks, pull requests merged in 2020-06, with the labels that each got.

#35 Fix issue with intermittent auth issues
  app/controllers/defra_ruby_mocks/company_controller.rb
  app/controllers/defra_ruby_mocks/worldpay_controller.rb
Labels: bug

#36 Refactor worldpay controller
  app/controllers/defra_ruby_mocks/worldpay_api_controller.rb
  app/controllers/defra_ruby_mocks/worldpay_controller.rb
  app/views/defra_ruby_mocks/worldpay/stuck.html.erb
  app/views/defra_ruby_mocks/worldpay_api/payment_request.xml.erb
  app/views/defra_ruby_mocks/worldpay_api/refund_request.xml.erb
  config/routes.rb
  spec/requests/worldpay_api_spec.rb
  spec/requests/worldpay_spec.rb
Labels: housekeeping

#37 Revert "Refactor worldpay controller"
  app/controllers/defra_ruby_mocks/worldpay_api_controller.rb
  app/controllers/defra_ruby_mocks/worldpay_controller.rb
  app/views/defra_ruby_mocks/worldpay/payment_request.xml.erb
  app/views/defra_ruby_mocks/worldpay/refund_request.xml.erb
  app/views/defra_ruby_mocks/worldpay/stuck.html.erb
  config/routes.rb
  spec/requests/worldpay_api_spec.rb
  spec/requests/worldpay_spec.rb
Labels: housekeeping

#38 Add mocking of pending Worldpay payments
  README.md
  app/controllers/defra_ruby_mocks/worldpay_controller.rb
  app/services/defra_ruby_mocks/worldpay_response_service.rb
  spec/requests/worldpay_spec.rb
  spec/services/worldpay_response_service_spec.rb
Labels: enhancement

#39 Add mocking of cancelled Worldpay payments
  README.md
  app/controllers/defra_ruby_mocks/worldpay_controller.rb
  app/services/defra_ruby_mocks/worldpay_response_service.rb
  spec/requests/worldpay_spec.rb
  spec/services/worldpay_response_service_spec.rb
Labels: enhancement

#40 Add mocking of errored Worldpay payments
  README.md
  app/controllers/defra_ruby_mocks/worldpay_controller.rb
  app/services/defra_ruby_mocks/worldpay_response_service.rb
  spec/requests/worldpay_spec.rb
  spec/services/worldpay_response_service_spec.rb
Labels: enhancement

#41 Log errors in worldpay controller
  app/controllers/defra_ruby_mocks/worldpay_controller.rb
Labels: enhancement

#43 Upgrade rails and ruby
  .ruby-version
  .travis.yml
  Gemfile.lock
  app/services/defra_ruby_mocks/base_service.rb
  bin/rails
  defra_ruby_mocks.gemspec
  spec/requests/company_spec.rb
  spec/requests/worldpay_spec.rb
  spec/spec_helper.rb
Labels: enhancement
